use fabsl with long double
prevents compile warning:

modules/s2-geometry-library/geometry/util/math/mathutil.h:109:45: error: absolute value function 'fabs' given an argument of type 'long double' but has parameter of type 'double' which may
      cause truncation of value [-Werror,-Wabsolute-value]
    const double kTolerance = epsilon * max(fabs(2 * b * b), fabs(4 * a * c));
                                            ^
modules/s2-geometry-library/geometry/util/math/mathutil.h:109:45: note: use function 'std::abs' instead
    const double kTolerance = epsilon * max(fabs(2 * b * b), fabs(4 * a * c));
                                            ^~~~
                                            std::abs
modules/s2-geometry-library/geometry/util/math/mathutil.h:109:45: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
modules/s2-geometry-library/geometry/util/math/mathutil.h:109:62: error: absolute value function 'fabs' given an argument of type 'long double' but has parameter of type 'double' which may
      cause truncation of value [-Werror,-Wabsolute-value]
    const double kTolerance = epsilon * max(fabs(2 * b * b), fabs(4 * a * c));
                                                             ^
modules/s2-geometry-library/geometry/util/math/mathutil.h:109:62: note: use function 'std::abs' instead
    const double kTolerance = epsilon * max(fabs(2 * b * b), fabs(4 * a * c));
                                                             ^~~~
                                                             std::abs
modules/s2-geometry-library/geometry/util/math/mathutil.h:109:62: note: include the header <cmath> or explicitly provide a declaration for 'std::abs'
modules/s2-geometry-library/geometry/util/math/mathutil.h:110:13: error: absolute value function 'fabs' given an argument of type 'long double' but has parameter of type 'double' which may
      cause truncation of value [-Werror,-Wabsolute-value]
    return (fabs(discriminant) <= kTolerance);
            ^

Signed-off-by: Daniel Black <daniel.black@au.ibm.com>